### ISSUE TITLE
Support different target volume size

### ISSUE THREAD

**Issue by GoogleCodeExporter** [brailleapps/dotify#102]
```
Currently when two volume-templates have a different value for 
sheets-in-volume-max, Dotify says: 

WARNING: Implementation does not support different target volume size. All 
volumes must have the same target size.
```

Original issue reported on code.google.com by `bertfrees` on 3 Feb 2015 at 2:33

**Comment by bertfrees** [comment]
See test [volume-template-various-sheets-in-volume-max](https://rawgit.com/snaekobbi/dotify/168c50fe265c9b007cf5557b95b0b1bf4fe44201/dotify.formatter.impl/test/org.daisy.dotify.engine.impl.resource-files.tests-overview.html#dp2/volume-template-various-sheets-in-volume-max-input.obfl)

**Comment by bertfrees** [comment]
@joeha480 I believe you fixed this?

**Comment by joeha480** [comment]
Me too. :) Thanks!
