### ISSUE TITLE
Initial page number is assumed to be odd

### ISSUE THREAD

**Issue by joeha480** [brailleapps/dotify#134]
There is a mix up of e.g. sheet calculation and initial page number which has the consequence that initial page number must be set to an odd number, or some calculations will be incorrect.

**Comment by bertfrees** [comment]
Right. I noticed that and wondered if that was intentional or not.

**Comment by bertfrees** [comment]
@joeha480 Can you give an example of what this issue is about? At first I assumed you meant that

```xml
<template use-when="(= (% $page 2) 1)">
  ...
</template>
```

can not be reliably used when `initial-page-number` is also used, but now I'm not sure anymore.

**Comment by bertfrees** [comment]
Or is this about the issue that the first page of a sequence with `initial-page-number="2"` is seen as a left-hand page so that the page numbers of the next sequence are one off? Yeah, I think that's it. The other example I gave is expected behavior, right?

**Comment by bertfrees** [comment]
I have fixed this locally.

**Comment by bertfrees** [comment]
This issue can be closed. I fixed this in https://github.com/brailleapps/dotify.formatter.impl/commit/61f608ee346f749ab0f72f7c863b36c3769be660 and I have moved the issue of being able to easily determine the side of a page inside `<template use-when="..."` to https://github.com/brailleapps/dotify.formatter.impl/issues/34.

**Comment by joeha480** [comment]
Ok, thanks!
