### ISSUE TITLE
PEF validation fails with "Rows do not fit within the defined page height" when row-spacing combined with footer

### ISSUE THREAD

**Issue by bertfrees** [brailleapps/dotify#196]
This OBFL

``` xml
<obfl version="2011-1" xml:lang="und" hyphenate="false">
  <layout-master name="main" duplex="true" page-width="10" page-height="10">
    <default-template>
      <header/>
      <footer>
        <field>
          <current-page number-format="default"/>
        </field>
      </footer>
    </default-template>
  </layout-master>
  <sequence master="main">
    <block row-spacing="2.0">
      ⠿⠿⠿⠿ ⠿⠿⠿⠿ ⠿⠿⠿⠿ ⠿⠿⠿⠿ ⠿⠿⠿⠿ ⠿⠿⠿⠿
      ⠿⠿⠿⠿ ⠿⠿⠿⠿ ⠿⠿⠿⠿ ⠿⠿⠿⠿ ⠿⠿⠿⠿ ⠿⠿⠿⠿
      ⠿⠿⠿⠿ ⠿⠿⠿⠿ ⠿⠿⠿⠿ ⠿⠿⠿⠿ ⠿⠿⠿⠿ ⠿⠿⠿⠿
    </block>
  </sequence>
</obfl>

```

results into this PEF

``` xml
<pef version="2008-1">
  <body>
    <volume cols="10" rows="10" rowgap="0" duplex="true">
      <section>
        <page>
          <row rowgap="4">⠿⠿⠿⠿⠀⠿⠿⠿⠿</row>
          <row rowgap="4">⠿⠿⠿⠿⠀⠿⠿⠿⠿</row>
          <row rowgap="4">⠿⠿⠿⠿⠀⠿⠿⠿⠿</row>
          <row rowgap="4">⠿⠿⠿⠿⠀⠿⠿⠿⠿</row>
          <row rowgap="4">⠿⠿⠿⠿⠀⠿⠿⠿⠿</row>
          <row>⠼⠁</row>
        </page>
        <page>
          <row rowgap="4">⠿⠿⠿⠿⠀⠿⠿⠿⠿</row>
          <row rowgap="4">⠿⠿⠿⠿⠀⠿⠿⠿⠿</row>
          <row rowgap="4">⠿⠿⠿⠿⠀⠿⠿⠿⠿</row>
          <row rowgap="4">⠿⠿⠿⠿⠀⠿⠿⠿⠿</row>
          <row/>
          <row>⠼⠃</row>
        </page>
      </section>
    </volume>
  </body>
</pef>
```

The last row of the first page does not fit on the page. Note that a footer with more than one line does not result in more rows possibly not fitting on the page.

**Comment by bertfrees** [comment]
Added test.

**Comment by bertfrees** [comment]
@joeha480 The problem is that the splitting happens without any information about the header or footer. `SplitPointHandler` doesn't distinguish between a split point "at the end of a page" or a split point "at the end of the main page area but before the footer". In both cases the last row before the break point takes up "1" space, even if the row spacing is greater than 1 (see `RowGroup.getLastUnitSize()` and `SizeStep.overflows()`). However, when the resulting rows from `SplitPointHandler` have been added to the page together with the footer (in `PageSequenceBuilder2`), that same row takes up more than "1" because it is not the last row in the context of the whole page. This causes the invalid state.

Now the question is how to fix it. It depends on the desired behavior of row-spacing. Do we have to make sure the 5th row doesn't end up on the first page? Or do we need to give the 5th row a row height of 1 so that it fits on the page?

**Comment by bertfrees** [comment]
Because you can do row-spacing inside the header, and this results in an empty row between the header and the main page area, something similar should probably happen with the footer.

**Comment by joeha480** [comment]
This is not difficult to fix. I have started on it, but I can't make a release of it today, because it requires some more thought. I'll fix it when I get back from vacation.

**Comment by bertfrees** [comment]
OK

**Comment by bertfrees** [comment]
PR for test: https://github.com/brailleapps/dotify.formatter.impl/pull/8

**Comment by bertfrees** [comment]
@joeha480 What is the status of this issue? You said you had started on it, but that it required more thought. Turns out that it is a problem for NLB after all, and they would like to fix it within the current sprint. If it is not fixed yet in the latest version of Dotify I can do it.

**Comment by bertfrees** [comment]
> [...] Do we have to make sure the 5th row doesn't end up on the first page? Or do we need to give the 5th row a row height of 1 so that it fits on the page?

You could say that the first option respects the input OBFL best: a "row-spacing" is specified so there must be an effective row-spacing.

Nevertheless I think I'm going for the second option because it is more flexible. It will make it possible to make your footer line touch the last row of the page body, but you may also force a minimum of one empty row between page body and footer by inserting an empty footer line.
