### ISSUE TITLE
Manual volume breaking does not work in combination with table-of-contents

### ISSUE THREAD

**Issue by bertfrees** [brailleapps/dotify#212]

**Comment by joeha480** [comment]
Some description would be appreciated.

By the way, if you make more issues / commits, please do so under brailleapps/dotify.formatter.impl

**Comment by bertfrees** [comment]
I thought the test would explain it. I don't have more information. I've made the test in brailleapps/dotify.formatter.impl, but I was unsure whether new issues should be made in there as well. (I thought you didn't like issues to be scattered over several repos.) But I'll make issues in dotify.formatter.impl in the future.

**Comment by joeha480** [comment]
Thanks. Well, maybe I am more comfortable with Github now, but I think I'll try to manage issues for each repo. But I also have a organization wide issue repo too for issues that doesn't really relate to a single repo.

I was just curious about what happened, but I guess I'll have to run the test.

**Comment by bertfrees** [comment]
PR for test: https://github.com/brailleapps/dotify.formatter.impl/pull/5

**Comment by joeha480** [comment]
Fixed in dotify.formatter.impl:2.7.0
