### ISSUE TITLE
No formalized set of CLI arguments

### ISSUE THREAD

**Issue by GoogleCodeExporter** [brailleapps/dotify#81]
```
There is no formalized set of CLI arguments. This means that some features are 
not available unless you already know about them.

Some formalization is required.
```

Original issue reported on code.google.com by `joel.hak...@mtm.se` on 21 Jan 2014 at 8:04

**Comment by joeha480** [comment]
The generic nature of this issue could potentially keep it open forever. However, it can be considered solved in dotify.task-api:2.2.0 even though a "formal" (i.e. limited) set of CLI arguments isn't provided. Should this prove insufficient, please create a new issue.
